### ISSUE TITLE
All value coming null -  

### ISSUE THREAD

**Issue by Arshit007** [JoMingyu/google-play-scraper#104]
**google_play_scraper.VERSION**
Write result of `google_play_scraper.VERSION`

**Describe the bug**
All value coming null.

**Code**
{'title': None, 'description': None, 'descriptionHTML': None, 'summary': None, 'summaryHTML': None, 'installs': None, 'minInstalls': None, 'score': None, 'ratings': None, 'reviews': None, 'histogram': [0, 0, 0, 0, 0], 'price': None, 'free': None, 'currency': None, 'sale': False, 'saleTime': None, 'originalPrice': None, 'saleText': None, 'offersIAP': False, 'inAppProductPrice': None, 'size': None, 'androidVersion': None, 'androidVersionText': None, 'developer': None, 'developerId': None, 'developerEmail': None, 'developerWebsite': None, 'developerAddress': None, 'privacyPolicy': None, 'developerInternalID': None, 'genre': None, 'genreId': None, 'icon': None, 'headerImage': None, 'screenshots': [], 'video': None, 'videoImage': None, 'contentRating': None, 'contentRatingDescription': None, 'adSupported': None, 'containsAds': False, 'released': None, 'updated': None, 'version': [None, [[[[[None, [None, [[None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/PgphCA3N_CSH_mLekZ_0RHiXS7FOUSlZdaCIwmEGZ2Q7I4eJkJVvYSb6Q3Lt8YP3LPZf'], None, None, None, None, None, 2], [None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/PgphCA3N_CSH_mLekZ_0RHiXS7FOUSlZdaCIwmEGZ2Q7I4eJkJVvYSb6Q3Lt8YP3LPZf'], None, None, None, None, None, 2], [None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/PgphCA3N_CSH_mLekZ_0RHiXS7FOUSlZdaCIwmEGZ2Q7I4eJkJVvYSb6Q3Lt8YP3LPZf'], None, None, None, None, None, 2]], 2, 2], 'Slugterra: Slug it Out 2', None, [[['Epic Story Interactive', [None, None, None, None, [None, None, '/store/apps/dev?id=5905438781451669270']], True]], [None, [None, [None, 'Pick up Greneater, Aquafreak, and Nightgeist in the Ghoul Slug Pack!']]]], [], [[None, None, [None, ['4.6', 4.6215353]]]], [], [5, 4, 5], [None, None, None, None, [None, None, '/store/apps/details?id=com.dhxmedia.slugitout2']], None, ['CAIaYAofEh0KF2NvbS5kaHhtZWRpYS5zbHVnaXRvdXQyEAEYAxAAMhMI0/7dq5yG8wIVD4ynCh1uEAPjchMI7Kzeq5yG8wIVVhRiCh0S2QVAigENCAASCQoFZW4tVVMQAJgBAaoCbBpqCAASHwodChdjb20uZGh4bWVkaWEuc2x1Z2l0b3V0MhABGANKEwjT/t2rnIbzAhUPjKcKHW4QA+OaARMI7Kzeq5yG8wIVVhRiCh0S2QVA+gEPCg0IABIJCgVlbi1VUxAAiAIBygIECAEQAQ=='], ['com.dhxmedia.slugitout2', 7]], [None, [None, [[None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/P68oJSf3B2Pmb9acII34q5YXhZmAn-IIzsmaOJ05h374u1X4obrBZ5W6Hoxs--kWgQ']], [None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/P68oJSf3B2Pmb9acII34q5YXhZmAn-IIzsmaOJ05h374u1X4obrBZ5W6Hoxs--kWgQ']], [None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/P68oJSf3B2Pmb9acII34q5YXhZmAn-IIzsmaOJ05h374u1X4obrBZ5W6Hoxs--kWgQ']]], 2, 2], 'BEYBLADE BURST app', None, [[['Hasbro Inc.', [None, None, None, None, [None, None, '/store/apps/developer?id=Hasbro+Inc.']], True]], [None, [None, [None, 'Create, customize and battle your BEYBLADE BURST tops online']]]], [], [[None, None, [None, ['4.4', 4.3636756]]]], [], [5, 4, 5], [None, None, None, None, [None, None, '/store/apps/details?id=com.hasbro.beybladesenterprise']], None, ['CAIaZwomEiQKHmNvbS5oYXNicm8uYmV5YmxhZGVzZW50ZXJwcmlzZRABGAMQATITCNP+3auchvMCFQ+MpwodbhAD43ITCOys3quchvMCFVYUYgodEtkFQIoBDQgAEgkKBWVuLVVTEACYAQOqAnMacQgBEiYKJAoeY29tLmhhc2Jyby5iZXlibGFkZXNlbnRlcnByaXNlEAEYA0oTCNP+3auchvMCFQ+MpwodbhAD45oBEwjsrN6rnIbzAhVWFGIKHRLZBUD6AQ8KDQgAEgkKBWVuLVVTEACIAgPKAgQIAxAB'], ['com.hasbro.beybladesenterprise', 7]], [None, [None, [[None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/EgO34BOGEhnGGd0Yk4HRppcYAF8RNF7-WCe0Y2j6rzvn5CGQlrQj6BxaCRT5h7PdnA']], [None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/EgO34BOGEhnGGd0Yk4HRppcYAF8RNF7-WCe0Y2j6rzvn5CGQlrQj6BxaCRT5h7PdnA']], [None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/EgO34BOGEhnGGd0Yk4HRppcYAF8RNF7-WCe0Y2j6rzvn5CGQlrQj6BxaCRT5h7PdnA']]], 2, 2], 'Pokémon Quest', None, [[['The Pokemon Company', [None, None, None, None, [None, None, '/store/apps/developer?id=The+Pokemon+Company']], True]], [None, [None, [None, 'Pokémon Quest—a rambunctious expedition RPG featuring cube-shaped Pokémon!']]]], [], [[None, None, [None, ['4.3', 4.286546]]]], [], [5, 4, 5], [None, None, None, None, [None, None, '/store/apps/details?id=jp.pokemon.pokemonquest']], None, ['CAIaYAofEh0KF2pwLnBva2Vtb24ucG9rZW1vbnF1ZXN0EAEYAxACMhMI0/7dq5yG8wIVD4ynCh1uEAPjchMI7Kzeq5yG8wIVVhRiCh0S2QVAigENCAASCQoFZW4tVVMQAJgBA6oCbBpqCAISHwodChdqcC5wb2tlbW9uLnBva2Vtb25xdWVzdBABGANKEwjT/t2rnIbzAhUPjKcKHW4QA+OaARMI7Kzeq5yG8wIVVhRiCh0S2QVA+gEPCg0IABIJCgVlbi1VUxAAiAIDygIECAMQAQ=='], ['jp.pokemon.pokemonquest', 7]], [None, [None, [[None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/3fp2B459bCUBPM1b9uVBbeB5Gse2PNDLd9W5ySIP6ZZHAuUiAiLWHqO1WtQfEb16CiE'], None, None, None, None, None, 2], [None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/3fp2B459bCUBPM1b9uVBbeB5Gse2PNDLd9W5ySIP6ZZHAuUiAiLWHqO1WtQfEb16CiE'], None, None, None, None, None, 2], [None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/3fp2B459bCUBPM1b9uVBbeB5Gse2PNDLd9W5ySIP6ZZHAuUiAiLWHqO1WtQfEb16CiE'], None, None, None, None, None, 2]], 2, 2], 'WildCraft: Animal Sim Online 3D', None, [[['Turbo Rocket Games', [None, None, None, None, [None, None, '/store/apps/dev?id=6804371481370659921']], True]], [None, [None, [None, 'Explore the wild world with custom animals. Play this free online simulator game']]]], [], [[None, None, [None, ['4.5', 4.4502964]]]], [], [5, 4, 5], [None, None, None, None, [None, None, '/store/apps/details?id=com.turborocketgames.wildcraft']], None, ['CAIaZwomEiQKHmNvbS50dXJib3JvY2tldGdhbWVzLndpbGRjcmFmdBABGAMQAzITCNP+3auchvMCFQ+MpwodbhAD43ITCOys3quchvMCFVYUYgodEtkFQIoBDQgAEgkKBWVuLVVTEACYAQOqAnMacQgDEiYKJAoeY29tLnR1cmJvcm9ja2V0Z2FtZXMud2lsZGNyYWZ0EAEYA0oTCNP+3auchvMCFQ+MpwodbhAD45oBEwjsrN6rnIbzAhVWFGIKHRLZBUD6AQ8KDQgAEgkKBWVuLVVTEACIAgPKAgQIAxAB'], ['com.turborocketgames.wildcraft', 7]], [None, [None, [[None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/XOmuW3vBxKTPtOBE4py28VfDKrC2cYFBkQbo8GlslONO58-z-FevWjczgKKwDcT-Fg'], None, None, None, None, None, 2], [None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/XOmuW3vBxKTPtOBE4py28VfDKrC2cYFBkQbo8GlslONO58-z-FevWjczgKKwDcT-Fg'], None, None, None, None, None, 2], [None, 2, [512, 512], [None, None, 'https://play-lh.googleusercontent.com/XOmuW3vBxKTPtOBE4py28VfDKrC2cYFBkQbo8GlslONO58-z-FevWjczgKKwDcT-Fg'], None, None, None, None, None, 2]], 2, 2], 'Axolochi', None, [[['HyperBeard', [None, None, None, None, [None, None, '/store/apps/dev?id=8149813369190878382']], True]], [None, [None, [None, 'Hatch super cute axolotls and watch them grow into different shapes and colors!']]]], [], [[None, None, [None, ['4.6', 4.647726]]]], [], [5, 4, 5], [None, None, None, None, [None, None, '/store/apps/details?id=com.hyperbeard.axolochi']], None, ['CAIaYAofEh0KF2NvbS5oeXBlcmJlYXJkLmF4b2xvY2hpEAEYAxAEMhMI0/7dq5yG8wIVD4ynCh1uEAPjchMI7Kzeq5yG8wIVVhRiCh0S2QVAigENCAASCQoFZW4tVVMQAJgBA6oCbBpqCAQSHwodChdjb20uaHlwZXJiZWFyZC5heG9sb2NoaRABGANKEwjT/t2rnIbzAhUPjKcKHW4QA+OaARMI7Kzeq5yG8wIVVhRiCh0S2QVA+gEPCg0IABIJCgVlbi1VUxAAiAIDygIECAMQAQ=='], ['com.hyperbeard.axolochi', 7]]], 'Similar', None, [None, None, None, None, [None, None, '/store/apps/collection/cluster?clp=ogonCBEqAggIMh8KGWNvbS5uaWFudGljbGFicy5wb2tlbW9uZ28QARgD:S:ANO1ljKcNx0&gsr=CiqiCicIESoCCAgyHwoZY29tLm5pYW50aWNsYWJzLnBva2Vtb25nbxABGAM%3D:S:ANO1ljLVe3w']], True, 2, None, [None, 'CjWC0_-4Ay8KJvqegZ0DIAgFEM6-zd4HEI7F-vQHEP7f4aYBEJuKpogMEJzHgOcHEJS4qaG_LxAFGiqiCicIESoCCAgyHwoZY29tLm5pYW50aWNsYWJzLnBva2Vtb25nbxABGAM'], True], None, None, ['CBSqARUKEwi8k+GrnIbzAhUPjKcKHW4QA+M=']]], None, [], True], 'recentChanges': None, 'recentChangesHTML': None, 'comments': [], 'editorsChoice': False, 'appId': 'com.nianticlabs.pokemongo', 'url': 'https://play.google.com/store/apps/details?id=com.nianticlabs.pokemongo&hl=en&gl=us'

```
```

**Expected behavior**
A description of what you expected to happen.

**Additional context**

**Comment by wtrevisan-cit** [comment]
Same issue here!

**Comment by Arshit007** [comment]
I figured it out because of the version update,older version was not working,try using the latest version(1.0.2),it will work.

**Comment by tinker1992** [comment]
I also upgrade it to 1.0.2, and it worked :)
