### ISSUE TITLE
[BUG] test_app.py returns now 5 failures out of 6 tests

### ISSUE THREAD

**Issue by Franky4242** [JoMingyu/google-play-scraper#105]
**google_play_scraper.1.0.1**
Executing test_app.py's tests gives 5 failures out of 6 tests

**Describe the bug**
It seems that google have changed their format and almost all fields remain to None when scrapping with app().

**Code**
see test_app.py

```
```

**Expected behavior**
A description of what you expected to happen.

**Additional context**

**Comment by Stonedge** [comment]
The npm Scrapper seems to have identify the change made by google:

mappers/details.js - MAPPING object

Change all ds:3 to ds:4
Change all ds:8 to ds:3
Change all ds:6 to ds:7
Change all ds:5 to ds:6

Just Sharing info in case it could help :)

ref: https://github.com/facundoolano/google-play-scraper/issues/480

**Comment by Franky4242** [comment]
Thanks @Stonedge 
Waiting for an official update, I was able to fix the issue with an update of constants/element.py
The ds number is the first parameter of ElementSpec()

**Comment by JoMingyu** [comment]
This issue already fixed at version 1.0.2. related: #102
