### ISSUE TITLE
How to get overall App Ratings? 

### ISSUE THREAD

**Issue by tinker1992** [JoMingyu/google-play-scraper#110]
Dear JoMingyu,

I was using another package to get iOS App related information called AppStoreScraper, it reads overall App Ratings for all launch countries, therefore I want to ask how can we use google-play-scraper to get overall App Rating? Is that possible to enter multiple countries in one time? Thanks a lot & happy new year!

**Comment by fab10m** [comment]
Look at the result fields "score" and "ratings".

**Comment by JoMingyu** [comment]
Due to the design of the google play webpage, only one country's results can be obtained at a time.
