### ISSUE TITLE
Get null in response

### ISSUE THREAD

**Issue by Chhunneng** [JoMingyu/google-play-scraper#114]
**google_play_scraper.1.0.3**
Write result of `google_play_scraper.1.0.3`

**Describe the bug**
I got `null` for all result from `google_play_scraper.app()`.

**Code**
Copy and paste the code that have issue.

```py
from google_play_scraper import app

data = app(
    "com.nianticlabs.pokemongo",
    lang="en",  # defaults to 'en'
    country="us",  # defaults to 'us'
)
```

this is the result 
```json
{
   "title":null,
   "description":null,
   "descriptionHTML":null,
   "summary":null,
   "summaryHTML":null,
   "installs":null,
   "minInstalls":null,
   "score":null,
   "ratings":null,
   "reviews":null,
   "histogram":[
      0,
      0,
      0,
      0,
      0
   ],
   "price":null,
   "free":null,
   "currency":null,
   "sale":false,
   "saleTime":null,
   "originalPrice":null,
   "saleText":null,
   "offersIAP":false,
   "inAppProductPrice":null
}
```

**Expected behaviour**
I expected to get all data without `null`.

**Additional context**
I am not clear if I'm wrong. Please correct and help with this code.

**Comment by JoMingyu** [comment]
Try after upgrade google-play-scraper to newest version with `pip install google-play-scraper --upgrade`.
