### ISSUE TITLE
Is it possible to get the version of a beta app?

### ISSUE THREAD

**Issue by shifoc** [JoMingyu/google-play-scraper#120]
WhatsApp Beta for example

**Comment by JoMingyu** [comment]
Please leave the expected behavior and actual behavior of the library function.

**Comment by shifoc** [comment]
Apps have Beta versions as well as stable versions. Using the library I can only see stable versions and not Beta ones.

**Comment by JoMingyu** [comment]
Beta apps just appears on Google Play? I cannot see beta version of `WhatsApp` on Google Play.

**Comment by JoMingyu** [comment]
This library crawls Google Play webpage. So, crawler cannot extract data that doesn't appear on Google Play. I'll close this stale issue, so reopen or checkout new issue if the problem is still exist.
