### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by faraz-bst** [JoMingyu/google-play-scraper#128]
**google_play_scraper.VERSION**
1.1.0

**Describe the bug**
response no longer contains the key `size` which was previously present in the response or can be referred from the Repo's [README.md](https://github.com/JoMingyu/google-play-scraper#readme)

**Code**
```python
result = app(
    'com.nianticlabs.pokemongo',
    lang='en', # defaults to 'en'
    country='us' # defaults to 'us'
)
```
**Expected behavior**
Key 'size` should be contained in the response along with other keys
```python
{
  "size": "94M",
}
```
**Additional context**
Found a commit where the code for `size` was commented - https://github.com/JoMingyu/google-play-scraper/commit/d53bbf383b93a5e9ece0a22eae9176449a646227

**Comment by JoMingyu** [comment]
I changed the example. Thanks you.

**Comment by faraz-bst** [comment]
Are there any plans of adding the `size` key going forward @JoMingyu?
