### ISSUE TITLE
[BUG] app() doesn't return any app data , only return review text

### ISSUE THREAD

**Issue by NupuraW** [JoMingyu/google-play-scraper#135]
**google_play_scraper.1.1.0**

**Describe the bug**
app_meta = app(
                'com.webserveis.batteryinfo',
                lang='en',  # defaults to 'en'
                country='us'  # defaults to 'us'
            )
doesn't return any data about app. all the fields are None or null

**Code**
Copy and paste the code that have issue.

```
```

**Expected behavior**
should return  data such as title, developer ,price, description,rating ,intstalls

**Additional context**

**Comment by kluhan** [comment]
@NupuraW, are you sure you are using the latest version of Google Play Scraper? I just tested it for 10k apps and everything works fine for me.
Maybe Google is rolling out an update that is causing the problems, but then I can't fix it until I have the problem too.

**Comment by NupuraW** [comment]
I'm using the latest version. 1.1.0.

**Comment by NupuraW** [comment]
does it depend on anything else to pull data?

**Comment by kluhan** [comment]
no, as far as i know there are no dependencies except python >= 3.6.

no, currently there is no way to use a proxy, but you can open a feature request, maybe more people need such a feature. a workaround would be to simply redirect all tcp traffic to a proxy. you could try a tool like redsocks [https://github.com/darkk/redsocks](url) if you have a suitable proxy server. please let me know if you are successful with this or if you find another solution.

**Comment by crowley285** [comment]
@rossoft  Thanks for verifying
Interesting, do you think that google doesn't send the same data when crawling from different countries?
Like in my case for australia when crawling from slovakia.

**Comment by crowley285** [comment]
The browser on the same computer opens the page without problems
The scraper also downloads the page but is unable to parse anything from it
I'm attaching what is returned by: /google_play_scraper/features/app.py:15 (dom = get(url))
[dom.txt](https://github.com/JoMingyu/google-play-scraper/files/9081419/dom.txt)

**Comment by 5sdba** [comment]
I'm having simmilar issue (everything is none) even on the latest version 1.2.0
doesn't return any data about app. all the fields are None or null

**Comment by 5sdba** [comment]
I'm using the latest version. 1.2.1

'version': 'Varies with device',

**Comment by ma9h9di** [comment]
I'm having similar issue (everything is none) even on the latest version 1.2.2
and I solved it by overwrite `Detail` in `ElementSpecs`  change all `ElementSpec(4, ...)` by `ElementSpec(5, ...)` because for me app date in `ds:5` not in `ds:4` 

I think Google changes the content of the pages according to the IP address of the users
My IP address is inside Iran

**Comment by rossoft** [comment]
@ma9h9di please check you are really using 1.2.2, as this change ElementSpec(4)  to ElementSpec(5) is precisely what is included in 1.2.2

**Comment by crowley285** [comment]
I pulled the latest changes and the issue seems to be resolved. So far i did not encounter any issues.

**Comment by JoMingyu** [comment]
@kluhan & @rossoft huge thanks to you help resolve this issue.
