### ISSUE TITLE
[FEAT-REQ] Extend limit of App Search number of results

### ISSUE THREAD

**Issue by quim-motger** [JoMingyu/google-play-scraper#141]
**Is your feature request related to a problem? Please describe.**
App Search by query is currently limited to 30 results. Isn't it possible to get all results through a pagination mechanism or similar?

**Describe the solution you'd like**
Extend the google_play_scraper.search feature to paginate results from Google Play.

**Describe alternatives you've considered**
--

**Additional context**
It is possible to get this information from Google Play, although it requires pagination management.

**Comment by siftnoorsingh** [comment]
This would be a great feature to have.

**Comment by milekey** [comment]
Is it possible? I can always see limited number (=< 30) of results on play.google.com.
If you think it possible, how does it work? Which URL query param is it to enable this pagination?
It seems that only the Google Play app can display more than 30 results.
I think we may need reverse engineering Google Play app or packet capturing to break the limit.

**Comment by JoMingyu** [comment]
It is impossible because Google Play does not support it. Sorry.

**Comment by milekey** [comment]
JoMingyu, I agree with you.
(Note that my previous comment was intended to quim-motger)
And thank you for this great library. Cheers! :)

**Comment by gabrielfiorelli** [comment]
Just for clarification, are you talking about this page:
https://play.google.com/store/search?q=merge&c=word
?

**Comment by gabrielfiorelli** [comment]
https://play.google.com/store/search?q=merge&c=apps

Page like that can return up to 250 results.
