### ISSUE TITLE
[BUG] Some app's information is not displayed

### ISSUE THREAD

**Issue by MaxMassov** [JoMingyu/google-play-scraper#146]
**google_play_scraper.1.2.0**
The result is:
{
  'title': None,
  'description': None,
  'descriptionHTML': None,
  'summary': None,
  'installs': None,
  'minInstalls': None,
  'realInstalls': None,
  'score': None,
  'ratings': None,
  'reviews': None,
  'histogram': [
    0,
    0,
    0,
    0,
    0
  ],
  'price': None,
  'free': None,
  'currency': None,
  'sale': False,
  'saleTime': None,
  'originalPrice': None,
  'saleText': None,
  'offersIAP': False,
  'inAppProductPrice': None,
  'developer': None,
  'developerId': None,
  'developerEmail': None,
  'developerWebsite': None,
  'developerAddress': None,
  'privacyPolicy': None,
  'genre': None,
  'genreId': None,
  'icon': None,
  'headerImage': None,
  'screenshots': [
    
  ],
  'video': None,
  'videoImage': None,
  'contentRating': None,
  'contentRatingDescription': None,
  'adSupported': None,
  'containsAds': False,
  'released': None,
  'updated': None,
  'version': 'Varies with device',
  'recentChanges': None,
  'recentChangesHTML': None,
  'comments': [
    
  ],
  'appId': 'app.example.com',
  'url': 'https://play.google.com/store/apps/details?id=app.example.com'
}

**Describe the bug**
Almost all the inforamtion about the app set as None

**Code**
from google_play_scraper import app
result = app(
                "app.example.com"
            )
print(result)

**Expected behavior**
I want to get full information about different apps from Google Play

**Additional context**
I suppose, there are some problems with `data_map` in `ElementSpec` class or `nested_lookup` function (I think, it should be added at the beginning: `if source is None: return ""`)

**Comment by FozerZ** [comment]
download last version 1.2.2
