### ISSUE TITLE
[BUG] Any properties from app() are being "None" but url, version and appId

### ISSUE THREAD

**Issue by swaggyp7** [JoMingyu/google-play-scraper#148]
**Version: 1.1.0**

I'm running the code from the example:
```
result = app(
    'com.nianticlabs.pokemongo',
    lang='en',  # defaults to 'en'
    country='us'  # defaults to 'us'
)
print(result) # {'title': None, 'description': None, 'descriptionHTML': None, 'summary': None, 'installs': None, 'minInstalls': None, 'score': None, 'ratings': None, 'reviews': None, 'histogram': [0, 0, 0, 0, 0], 'price': None, 'free': None, 'currency': None, 'sale': False, 'saleTime': None, 'originalPrice': None, 'saleText': None, 'offersIAP': False, 'inAppProductPrice': None, 'developer': None, 'developerId': None, 'developerEmail': None, 'developerWebsite': None, 'developerAddress': None, 'privacyPolicy': None, 'genre': None, 'genreId': None, 'icon': None, 'headerImage': None, 'screenshots': [], 'video': None, 'videoImage': None, 'contentRating': None, 'contentRatingDescription': None, 'adSupported': None, 'containsAds': False, 'released': None, 'updated': None, 'version': 'Varies with device', 'recentChanges': None, 'recentChangesHTML': None, 'comments': [], 'appId': 'com.nianticlabs.pokemongo', 'url': 'https://play.google.com/store/apps/details?id=com.nianticlabs.pokemongo&hl=en&gl=us'}
```
It doesn't work, **any properties are being "None" as what the title said.**
But when I tried function reviews(), Is worked well.

**Comment by Kedao98** [comment]
Version: 1.1.0
same problem. Im trying to run the code in linux, which returns the same data as above. But it works well in my Mac. 
`
result = app(
    'com.nianticlabs.pokemongo',
    lang='en',  # defaults to 'en'
    country='us'  # defaults to 'us'
)
>>> result
{'title': None, 'description': None, 'descriptionHTML': None, 'summary': None, 'installs': None, 'minInstalls': None, 'score': None, 'ratings': None, 'reviews': None, 'histogram': [0, 0, 0, 0, 0], 'price': None, 'free': None, 'currency': None, 'sale': False, 'saleTime': None, 'originalPrice': None, 'saleText': None, 'offersIAP': False, 'inAppProductPrice': None, 'developer': None, 'developerId': None, 'developerEmail': None, 'developerWebsite': None, 'developerAddress': None, 'privacyPolicy': None, 'genre': None, 'genreId': None, 'icon': None, 'headerImage': None, 'screenshots': [], 'video': None, 'videoImage': None, 'contentRating': None, 'contentRatingDescription': None, 'adSupported': None, 'containsAds': False, 'released': None, 'updated': None, 'version': 'Varies with device', 'recentChanges': None, 'recentChangesHTML': None, 'comments': [], 'appId': 'com.nianticlabs.pokemongo', 'url': 'https://play.google.com/store/apps/details?id=com.nianticlabs.pokemongo&hl=en&gl=us'}`

**Comment by JoMingyu** [comment]
Can you try after update the version to latest(1.2.2)?

**Comment by JoMingyu** [comment]
This issue occurs again on version 1.2.2, please reopen this issue.

**Comment by swaggyp7** [comment]
> Issue occurs again on version 1.2.2, please reopen this issue.

Okay, thx for your reply

**Comment by Kedao98** [comment]
> Issue occurs again on version 1.2.2, please reopen this issue.

thx for your reply. But i have some problem with upgrade to 1.2.2 with python3 version of 3.6. Is it support such version? I can not find 1.2.2 using pip, but 3.8&3.9 work well.

**Comment by alexspyr** [comment]
**Python 3.6.6 & google_play_scraper==1.2.2** 
same thing with almost everything being None.

**Comment by alexspyr** [comment]
+1 for not being able to find the 1.2.2 version on python 3.6

**Comment by swaggyp7** [comment]
> > Issue occurs again on version 1.2.2, please reopen this issue.
> 
> thx for your reply. But i have some problem with upgrade to 1.2.2 with python3 version of 3.6. Is it support such version? I can not find 1.2.2 using pip, but 3.8&3.9 work well.

I had this problem before because version 1.2.x does not exist in the pip old version, I don't know what the actual version of pip is, But it's could be found after I upgrade my pip to 22. x(the latest version). 
So you can't find 1.2.2 in python3.6 because the pip latest version does not support python3.6.

**Comment by swaggyp7** [comment]
> +1 for not being able to find the 1.2.2 version on python 3.6

Watch my last reply, You should upgrade your python to 3.7 at least. Then upgrade pip to 22.x(Maybe 21.x as well,I don't know the actual version which supports 1.2.2,But I installed the latest version of pip)
