### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hakobiant** [JoMingyu/google-play-scraper#149]
It was all good up till today, but for some reason it doesn't get the data anymore and shows 'none' for all the data.

Any idea what can be causing this? I am using the latest version.

Here is the code below that has been working fine up till today.

pip install google-play-scraper
from google_play_scraper import app
import pandas as pd
result = app('com.acheteza.asse', country = 'gl') 
result

**Comment by JoMingyu** [comment]
Can you try this after update the version?

**Comment by hakobiant** [comment]
I thought I've updated it, but apparently I haven't.

Just updated the library, then restarted the kernel again and now it gets the data.

Thanks for getting back to me and for the quick response.

**Comment by Balive13** [comment]
@hakobiant I did your suggestion but I still have the same issue. I think there is a problem in the latest version because I changed the latest version to v1.2.1 and now it works well.
