### ISSUE TITLE
Ready to co-working

### ISSUE THREAD

**Issue by JoMingyu** [JoMingyu/google-play-scraper#151]
- contribution guide
- branch protection rule
- etcs

**Comment by kluhan** [comment]
@JoMingyu, I am currently scheduling some time to work on the scraper. For one, I'm thinking about adapting the structure of the scraper to better handle dynamic data, as the current design has its limitations with more complex data like the data_safety-data. For another, I would like to add some functionality.

Should we continue working on the master via pull requests or open a development branch to collect some changes before releasing them to the master?

**Comment by JoMingyu** [comment]
@kluhan You may do as you please. Please just open the PR so that we can talk about the code.
