### ISSUE TITLE
README.md Update

### ISSUE THREAD

**Issue by gabrielfiorelli** [JoMingyu/google-play-scraper#154]
Don't know the best way to comment it, so, here we go.

The response is now returning values for **realInstalls**, with the real quantity of downloads. This isn't described in the README.md

`{
	"title": "Pokémon GO",
        "summary": "Discover Pokémon worldwide",
	"installs": "100,000,000+",
	"minInstalls": 100000000,
	"realInstalls": 449897250,
	"score": 4.2824965,
	"ratings": 15335075,
	"reviews": 978618
}`

**Comment by JoMingyu** [comment]
It added. Thanks.
