### ISSUE TITLE
How to verify the crawled app permission data?

### ISSUE THREAD

**Issue by ZorkJ** [JoMingyu/google-play-scraper#156]
Hi, 

I am quite curious about the app Permission data. I use following code as a test

```
from google_play_scraper import permissions

result = permissions(
    'com.nianticlabs.pokemongo',
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
)
result
```

and the result is 

```
{'Contacts': ['find accounts on the device', 'read your contacts'],
 'Phone': ['read phone status and identity'],
 'Storage': ['modify or delete the contents of your USB storage',
  'read the contents of your USB storage'],
 'Identity': ['find accounts on the device'],
 'Wi-Fi connection information': ['view Wi-Fi connections'],
 'Location': ['approximate location (network-based)',
  'precise location (GPS and network-based)'],
 'Camera': ['take pictures and videos'],
 'Photos/Media/Files': ['modify or delete the contents of your USB storage',
  'read the contents of your USB storage'],
 'Device ID & call information': ['read phone status and identity'],
 'Other': ['access Bluetooth settings',
  'control vibration',
  'full network access',
  'pair with Bluetooth devices',
  'prevent device from sleeping',
  'run at startup',
  'use accounts on the device',
  'view network connections'],
 'Uncategorized': ['receive data from Internet']}
```
​But this result is quite different with the **safety information** page:
https://play.google.com/store/apps/datasafety?id=com.nianticlabs.pokemongo&hl=en&gl=US.

For example, your result has no information on 

![image](https://user-images.githubusercontent.com/31822431/197175642-ee3cbcab-7076-48e8-9762-255202b11582.png)

So, I am quite curious about the resource you use to extract the permissions data. Could you mind help me?

Thanks

**Comment by kluhan** [comment]
Hello,
the app permissions have nothing to do with data safety from the scraper's point of view. In the past, Google removed the app permissions from the visible part of the Google Play Store and introduced the data safety page as a replacement about half a year ago. Nevertheless, the API to access the app permissions remained open. The scraper uses this API to load the app permissions even if they are currently not displayed on the Google Play Store. 
Currently, we are also working on making data safety accessible via this scraper but this feature is currently in early development and I wouldn't expect it before the month after next.

please reopen if you have further questions.
