### ISSUE TITLE
[FEAT-REQ] multiple categories/genere

### ISSUE THREAD

**Issue by ybdesire** [JoMingyu/google-play-scraper#158]
one App may has multiple categories, such as https://play.google.com/store/apps/details?id=com.cig.chineseparents.gp&hl=en
The genere should be a list as : ['Simulation', 'Life', 'Casual', 'Single player', 'Stylized', 'Anime']

But currently we can only get genere='Simulation'

So can we get multipe genere as a list for one App?

**Comment by kluhan** [comment]
@ybdesire I just looked at it and you are absolutely right, there is definitely the possibility of multiple genres. unfortunately, the data structure is not that easy to parse. so we will probably not add this feature until the next major update, which will hopefully allow us to extract complex structures more easily.
I will inform you here as soon as the feature is available

**Comment by ybdesire** [comment]
@kluhan  Thanks for the analysis and update . :) looking forward to hear from you.

**Comment by PowerToThePeople111** [comment]
I would be also interested in that feature. Just to let you know that there is more than 1 person who is actually interested.
