### ISSUE TITLE
How does sort feature work?

### ISSUE THREAD

**Issue by EuphoriaCelestial** [JoMingyu/google-play-scraper#159]
Hi @JoMingyu , thank you for a very useful repo, I just have a quick, short question: How does your sort by newest function work? I can't find the sorting code anywhere and what is the key/timestamp/... did you based on to sort?

**Comment by JoMingyu** [comment]
It uses what is provided by Google Play's query parameter unit. It's a little complicated, but you can see through [the part that builds the request body](https://github.com/JoMingyu/google-play-scraper/blob/350426ff813af2961bdbaa9fe3cf38e593fc50e8/google_play_scraper/constants/request.py#L34-L66).
