### ISSUE TITLE
Some apps report errors

### ISSUE THREAD

**Issue by DestroyLee** [JoMingyu/google-play-scraper#16]
This ’com.trixi.bike.stunts.driving‘ cannot be grabbed
`def unescape_text(s):
    return unescape(s.replace('<br>', '\r\n'))`

AttributeError: 'NoneType' object has no attribute 'replace'
Some fields do not match the value, but they are not processed.

**Comment by JoMingyu** [comment]
May response was too late, but a new patch will be released this week. sorry ;(

**Comment by JoMingyu** [comment]
it fixed in the [0.0.1.2 release](https://pypi.org/manage/project/google-play-scraper/release/0.0.1.2/).
