### ISSUE TITLE
[BUG] Most of the fields are null

### ISSUE THREAD

**Issue by nithi2023** [JoMingyu/google-play-scraper#165]
I am seeing most of the fields are null. I have tried this `com.wolfram.android.alpha` package with default settings. but, all of the responses were null except the comments.

`'title': None, 'description': None, 'descriptionHTML': None, 'summary': None, 'installs': None, 'minInstalls': None, 'score': None, 'ratings': None, 'reviews': None, 'histogram': [0, 0, 0, 0, 0], 'price': None, 'free': None, 'currency': None, 'sale': False, 'saleTime': None, 'originalPrice': None, 'saleText': None, 'offersIAP': False, 'inAppProductPrice': None, 'developer': None, 'developerId': None, 'developerEmail': None, 'developerWebsite': None, 'developerAddress': None, 'privacyPolicy': None, 'genre': None, 'genreId': None, 'icon': None, 'headerImage': None, 'screenshots': [], 'video': None, 'videoImage': None, 'contentRating': None, 'contentRatingDescription': None, 'adSupported': None, 'containsAds': False, 'released': None, 'updated': None, 'version': 'Varies with device', 'recentChanges': None, 'recentChangesHTML': None, 'comments': ['Impressive ability'title': None, 'description': None, 'descriptionHTML': None, 'summary': None, 'installs': None, 'minInstalls': None, 'score': None, 'ratings': None, 'reviews': None, 'histogram': [0, 0, 0, 0, 0], 'price': None, 'free': None, 'currency': None, 'sale': False, 'saleTime': None, 'originalPrice': None, 'saleText': None, 'offersIAP': False, 'inAppProductPrice': None, 'developer': None, 'developerId': None, 'developerEmail': None, 'developerWebsite': None, 'developerAddress': None, 'privacyPolicy': None, 'genre': None, 'genreId': None, 'icon': None, 'headerImage': None, 'screenshots': [], 'video': None, 'videoImage': None, 'contentRating': None, 'contentRatingDescription': None, 'adSupported': None, 'containsAds': False, 'released': None, 'updated': None, 'version': 'Varies with device', 'recentChanges': None, 'recentChangesHTML': None, 'comments': ['Impressive ability..'], 'appId': 'com.wolfram.android.alpha', 'url': 'https://play.google.com/store/apps/details?id=com.wolfram.android.alpha&hl=en&gl=us'}`

**Comment by JoMingyu** [comment]
Can you give me your library version? It works on my `1.2.2` version.
