### ISSUE TITLE
Error in fetching details of  com.instagram.igtv

### ISSUE THREAD

**Issue by ajinabraham** [JoMingyu/google-play-scraper#17]
Try fetching `com.instagram.igtv` 
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by JoMingyu** [comment]
My response was too late, but a new patch will be released this week. sorry ;(

**Comment by JoMingyu** [comment]
it fixed in the [0.0.1.3 release](https://pypi.org/manage/project/google-play-scraper/release/0.0.1.3/).
