### ISSUE TITLE
[BUG] Sort.NEWEST returns the same items as Sort.MOST_RELEVANT.

### ISSUE THREAD

**Issue by cheburashka5** [JoMingyu/google-play-scraper#187]
**Library version**
1.2.4

**Describe the bug**
Sort.NEWEST returns the same items as Sort.MOST_RELEVANT. They are both the MOST_RELEVANT items.

**Code**
from google_play_scraper import Sort, reviews

result = reviews(
    'com.google.android.youtube',
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.NEWEST
    count=10, # defaults to 100
)

print(result)

has identical items to 

from google_play_scraper import Sort, reviews

result = reviews(
    'com.google.android.youtube',
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.NEWEST
    count=10, # defaults to 100
)

**Expected behavior**
Sort.NEWEST should return the newest returns, not the most relevant.

**Comment by cheburashka5** [comment]
@JoMingyu, could you take a look please?

**Comment by JoMingyu** [comment]
@Meihb Nice work. I'll include it in the next release.

**Comment by JoMingyu** [comment]
It fixed at v1.2.6. Check it out!
