### ISSUE TITLE
Categories dublicates [BUG] 

### ISSUE THREAD

**Issue by Tsarikovich** [JoMingyu/google-play-scraper#193]
**Library version**
1.2.4

**Describe the bug**
When I try to retrieve the data about apps in the loop, "categories" field of next app containing categories of previous app.

**Code**
Copy and paste the code that have issue.

```
from google_play_scraper import app
apps_names = [ ]
for app_name in apps_names:    
   print(app(app_name)['categories'])
```

**Comment by ggouzi** [comment]
#198

**Comment by JoMingyu** [comment]
It seems fixed. Thanks to @ggouzi . I was really stupid :/
