### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position

### ISSUE THREAD

**Issue by zionchao** [JoMingyu/google-play-scraper#20]
need add  encoding in setup.py file,
 long_description=open("README.md",encoding="utf-8").read()

**Comment by ETOCheney** [comment]
need add encoding in setup.py file,
long_description=open("README.md",encoding="utf-8").read()

**Comment by yakir2b** [comment]
need add encoding in setup.py file,
long_description=open("README.md",encoding="utf-8").read()

**Comment by ETOCheney** [comment]
临时解决方法：
使用 
`pip install git+https://github.com/ETOCheney/google-play-scraper.git@master `

**Comment by JoMingyu** [comment]
My response was too late, but a new patch will be released this week. sorry ;(

**Comment by JoMingyu** [comment]
it fixed in the [0.0.1.2 release](https://pypi.org/manage/project/google-play-scraper/release/0.0.1.2/).
