### ISSUE TITLE
[BUG] Search doesn't return the first result when an app is featured

### ISSUE THREAD

**Issue by johannquerne** [JoMingyu/google-play-scraper#202]
**Library version**
1.2.4

**Describe the bug**
Search doesn't return the first result when an app is featured (see screenshot)
![Screenshot from 2023-11-30 16-54-10](https://github.com/JoMingyu/google-play-scraper/assets/2736484/f3220f8c-a176-4895-b946-b02ceffba6f3)

**Code**
results = google_play_scraper.search(
                'Instagram',
                lang='en', # defaults to 'en'
                country='US', # defaults to 'us',
                n_hits=20
            )

RESULTS

    {
      "name": "Layout from Instagram: Collage",
      "bundle": "com.instagram.layout",
      "icon": "https://play-lh.googleusercontent.com/S3QGLD_HzVLMsvH1jZ4hRdn66JAE94S12hvkbj5s7dG1SjhDh_KmHOoLCN_GgiIB9w"
    },
    {
      "name": "TikTok",
      "bundle": "com.zhiliaoapp.musically",
      "icon": "https://play-lh.googleusercontent.com/BmUViDVOKNJe0GYJe22hsr7juFndRVbvr1fGmHGXqHfJjNAXjd26bfuGRQpVrpJ6YbA"
    },
    {
      "name": "Facebook",
      "bundle": "com.facebook.katana",
      "icon": "https://play-lh.googleusercontent.com/KCMTYuiTrKom4Vyf0G4foetVOwhKWzNbHWumV73IXexAIy5TTgZipL52WTt8ICL-oIo"
    },
    {
      "name": "Messenger",
      "bundle": "com.facebook.orca",
      "icon": "https://play-lh.googleusercontent.com/ldcQMpP7OaVmglCF6kGas9cY_K0PsJzSSosx2saw9KF1m3RHaEXpH_9mwBWaYnkmctk"
    }

```
```

**Expected behavior**
Instagram app should be the first result

**Additional context**

**Comment by smit-kukadiya** [comment]
Any one get this solution??

**Comment by JoMingyu** [comment]
It fixed at v1.2.5!
