### ISSUE TITLE
질문있습니다ㅠ

### ISSUE THREAD

**Issue by objks** [JoMingyu/google-play-scraper#205]
안녕하세요

최신순으로 정렬이 안되는데 어떻게 수정해야될까요??

**Comment by JoMingyu** [comment]
사용하신 코드, expected behavior, actual behavior를 정리해주시면 알려드리기 더 쉬울 것 같습니다. 최근에 maintain을 많이 안 해서 실제로 버그가 맞을 수 있습니다. 그러니 샘플 주시면 빨리 수정해 볼게요.

**Comment by JoMingyu** [comment]
seems related to #187

**Comment by JoMingyu** [comment]
@objks v1.2.6으로 업데이트하면 될 것 같습니다.
