### ISSUE TITLE
[FEAT-REQ] [Get specific versions data only] : How to get the specific version data only ?

### ISSUE THREAD

**Issue by VinayChaudhari1996** [JoMingyu/google-play-scraper#225]
Hi @JoMingyu,

I have the following requirements:

- Retrieve all unique app versions along with their corresponding release dates via an API.
- Avoid scraping large amounts of data; instead, directly access specific versions.
- Filter and retrieve reviews only for the last 5 versions or based on a specified input.
- Ensure that I can efficiently obtain reviews for a particular version without pulling unnecessary data.

Currently, I’m requesting 10,000 reviews, then matching them against the latest version date from the app metadata to filter reviews for that version. However, I'd like to streamline this process. 

Is there an API or method available to achieve these goals more efficiently?

Thank you

**Comment by 3052** [comment]
> Retrieve all unique app versions along with their corresponding release dates via an API.

I don't think this is possible, unless someone is keeping their own database of versions. if someone actually know a way to get this info directly from Google - I can offer a 1000 USD bounty - contact me privately
