### ISSUE TITLE
can we extract  comment dates  and who made that comment?

### ISSUE THREAD

**Issue by Shyamniper** [JoMingyu/google-play-scraper#25]

**Comment by JoMingyu** [comment]
Good idea! It will be added as a new release on December 11.

**Comment by JoMingyu** [comment]
Feature is ready and will be released today in version 0.0.2.0.

**Comment by JoMingyu** [comment]
I'm sorry about my late follow-up

**Comment by JoMingyu** [comment]
The feature that retrieves the app's review data has been released with version 0.0.2.0 and has been fully tested in Python 3. The usage is written in the README. Sorry for being late, I hope it helps.

With code refactoring, performance optimizations, and feature additions, I'll be making a lot of improvements in version 0.0.2.1. Please wait for this too. If it works well, I'd appreciate pressing star.

**Comment by JoMingyu** [comment]
If feature has problem, open new issue for it.
