### ISSUE TITLE
more than 40 comments

### ISSUE THREAD

**Issue by martinbouhier** [JoMingyu/google-play-scraper#34]
I would like to know if I could extract all reviews of an app.
Thanks

**Comment by JoMingyu** [comment]
Hi martin,
I will research to add the feature to retrieve all of the large amount of
review data.

Thanks. Regards

2020년 1월 21일 (화) 오전 3:08, Martin Bouhier <notifications@github.com>님이 작성:

**Comment by kedar116** [comment]
Can we kindly know is this issue resolved?
I am also not getting more than 40 reviews.
Thanks!

**Comment by JoMingyu** [comment]
> Can we kindly know is this issue resolved?
> I am also not getting more than 40 reviews.
> Thanks!

I'm sorry, I'm doing some writing, so time allocation isn't easy.
At least February 7, I promise to provide the feature.

**Comment by JoMingyu** [comment]
Feature is ready and will be released today in version 0.0.2.0.

**Comment by JoMingyu** [comment]
I'm sorry about my late follow-up

**Comment by kedar116** [comment]
Thank you so much 😄.

**Comment by JoMingyu** [comment]
The feature that retrieves the app's review data has been released with version 0.0.2.0 and has been fully tested in Python 3. The usage is written in the README. Sorry for being late, I hope it helps.

With code refactoring, performance optimizations, and feature additions, I'll be making a lot of improvements in version 0.0.2.1. Please wait for this too. If it works well, I'd appreciate pressing star ⭐️

**Comment by JoMingyu** [comment]
If feature has problem, open new issue for it.
