### ISSUE TITLE
Increasing the count past 200 for reviews

### ISSUE THREAD

**Issue by jakemckenzie** [JoMingyu/google-play-scraper#39]
JoMingyu,

I would like to increase the capacity of the scraping past 200 reviews. Could you explain what issues there are with increasing the capacity of the scraper past this point?

I've read the "Setting count too high can cause problems. Because the maximum number of reviews per page supported by Google Play is 200, it is designed to pagination and recrawl by 200 until the number of results reaches count." bit you included.

Could you go into a little more detail about this issue? Maybe I could contribute to helping you come up with a solution to it.

Thanks,
Jake.

**Comment by JoMingyu** [comment]
If you want, you can set the count to a number over 200. Just because of the technical limitations, the crawl logic is executed as much as the ceil of count / 200, so entering a ridiculously large value can cause problems. I personally recommend using a value less than 2000.

**Comment by JoMingyu** [comment]
I thought while commenting, would it help if I developed a function that allows the function to retrieve the 'next review list' using the token returned? For example, if 1000 tokens are retrieved and the returned token 'eXamplE' is passed to the reviews function, the list of reviews is retrieved from 1000 or later items.

**Comment by jakemckenzie** [comment]
I'm not quite sure, I've been staring at how you grab the reviews and I'm unsure whether that would do it. I'll try to implement that myself on a fork and get back to you.

**Comment by dudem8z7l** [comment]
I think it is because we have to click the "show more" button to load more review. I also faced the same issue regarding the limitation of number of reviews that can be extracted from the script.

does anyone know how to click and load all the reviews?

**Comment by JoMingyu** [comment]
> I think it is because we have to click the "show more" button to load more review. I also faced the same issue regarding the limitation of number of reviews that can be extracted from the script.
> 
> does anyone know how to click and load all the reviews?

I will create new return value `continuation_token` of `reviews` function.
On version 0.0.2.3, you can use `continuation_token` argument for load more reviews.

**Comment by JoMingyu** [comment]
`Continuation token` feature had released on version 0.0.2.3. And this issue has been stale for a long time without being updated, so I will close it.
