### ISSUE TITLE
Country Default

### ISSUE THREAD

**Issue by tsp2123** [JoMingyu/google-play-scraper#43]
Hey JoMingyu, What are the country abbreviations you are using?

    country='us', # defaults to 'us'

I would specifically like to use Nigeria, but am unsure if it is NI or NG that you are using as its country code. Do let me know!

**Comment by JoMingyu** [comment]
I will add a reference of the country code specifications to readme.md.

**Comment by JoMingyu** [comment]
This issue has been stale for a long time without being updated, so I will close it.
