### ISSUE TITLE
Support google account login, device/country support

### ISSUE THREAD

**Issue by justinbass** [JoMingyu/google-play-scraper#44]
If google account login were supported, device/country support could be automated.

Note this app, which currently is not supported in US: https://play.google.com/store/apps/details?id=com.eckoh.powerni

There is a field reading "This app is incompatible with your device.".

The same app in UK: https://play.google.com/store/apps/details?id=com.eckoh.powerni&gl=uk

There is a field reading "This app is compatible with your device".

**Comment by JoMingyu** [comment]
Does this issue mean adding support for features related to google account login?

**Comment by JoMingyu** [comment]
I'll close this issue. it stayed too long without any conversation and seems to be invalid. re-raise the issue if this problem is valid.
