### ISSUE TITLE
Setting `continuation_token=continuation_token` fails

### ISSUE THREAD

**Issue by veliona** [JoMingyu/google-play-scraper#45]
## The problem

I tried to assign `continuation_token` to `continuation_token` argument as recommended in order to gather posts following the once that has already been crawled (the number set in `count` argument).
However, I am getting `IndexError: list index out of range` error.

## Specs
*  MacOS v 10.15.3 (19D76)

## Screenshots

![Screenshot 2020-04-25 at 16 06 34](https://user-images.githubusercontent.com/38378975/80282009-5b0c1880-870f-11ea-80ee-d45ef56df241.png)

**Comment by JoMingyu** [comment]
Set `lang`, `country`, `sort` arguments used in the first call. In your case,

```python
result, _ = reviews(
    'com.spotify.music',
    continuation_token=continuation_token,
    lang='pl',
    country='pl',
    sort=Sort.MOST_RELEVANT,
)
```

I'll add this to README.md, and apply it in version 0.0.2.4 so that it works well only continuation_token is used without any other parameters.

**Comment by veliona** [comment]
Thank you, this fixes it! I am closing the issue.
