### ISSUE TITLE
Deal Details

### ISSUE THREAD

**Issue by haideralipunjabi** [JoMingyu/google-play-scraper#48]
Google Play usually has many deals on games & apps. If such an app is scraped, it will return the deal price. Is it possible to fetch the original price as well?

**Comment by JoMingyu** [comment]
Can you provide any example about app has `deal`? It is better to provide a URL than capture.

**Comment by haideralipunjabi** [comment]
https://play.google.com/store/apps/details?id=air.pixelo

I don't know how long this deal will be active.

You can also find some of the deals on 

https://www.reddit.com/r/googleplaydeals/
