### ISSUE TITLE
How to get All Review?

### ISSUE THREAD

**Issue by irvanseptiar** [JoMingyu/google-play-scraper#53]
How to get All review with pagination?

**Comment by DXcarlos** [comment]
`def get_all_reviews(app_package, number_reviews_request, sort_type):

    logging.info('Start collecting reviews from {} app'.format(app_package))

    continuation_token = None
    total_reviews = []
    count = 0

    while True:

        try:
            result, continuation_token = reviews(
                app_package,
                lang='es',
                country='pe',
                sort=sort_type,
                continuation_token=continuation_token,
                count=number_reviews_request
            )
        except TypeError:
            break

        total_reviews.extend(result)
        count += len(result)

        logging.info('Number of reviews collected is {}'.format(count))

    return total_reviews`

**Comment by JoMingyu** [comment]
> I made this function it's simple but I think it's okay. Probably you need to change lang and country depending on your needs.
> 
> ```python
> def get_all_reviews(app_package, number_reviews_request, sort_type):
> 
>     logging.info('Start collecting reviews from {} app'.format(app_package))
> 
>     continuation_token = None
>     total_reviews = []
>     count = 0
> 
>     while True:
> 
>         try:
>             result, continuation_token = reviews(
>                 app_package,
>                 lang='es',
>                 country='pe',
>                 sort=sort_type,
>                 continuation_token=continuation_token,
>                 count=number_reviews_request
>             )
>         except TypeError:
>             break
> 
>         total_reviews.extend(result)
>         count += len(result)
> 
>         logging.info('Number of reviews collected is {}'.format(count))
> 
>     return total_reviews
> ```
> 
> ```python
> final_reviews = get_all_reviews('com.nianticlabs.pokemongo', 200, Sort.MOST_RELEVANT)
> ```

Good solution :) I'll implement new function `reviews_all` for these inconveniences.

**Comment by JoMingyu** [comment]
I'll notify here after `reviews_all` function has released.

**Comment by JoMingyu** [comment]
It released as version 0.0.3.0
