### ISSUE TITLE
In App Detail's app method the sum of histogram values doesn't match the total ratings

### ISSUE THREAD

**Issue by arunkumarchan** [JoMingyu/google-play-scraper#57]
I'm using the **app** method from google_play_scraper. I'm getting the list of numbers as Histogram. The expectation is the sum of the numbers in histogram should match with the totalratings variable. But I'm always finding the sum of histogram value is less than the total ratings. Refer the below for details

<img width="577" alt="Screen Shot 2020-07-14 at 6 30 36 PM" src="https://user-images.githubusercontent.com/11385222/87428663-56654b00-c600-11ea-8c46-0b86469e16ff.png">

**Comment by JoMingyu** [comment]
It seems to be issue from Google Play. I'll add some code that complements the problem.

Due : 2020-07-31 22:00:00 UTC+9

**Comment by JoMingyu** [comment]
I'm sorry for being late. Calibration logic added to version 0.0.3.2. Check it out!
