### ISSUE TITLE
reviews_all을 사용해도 전체 리뷰가 불러지지 않습니다.

### ISSUE THREAD

**Issue by sociengineer** [JoMingyu/google-play-scraper#59]
안녕하세요 정말 필요한 것을 미리 만들어주셔서 감사합니다.
특정 앱의 리뷰를 모두 긁고 싶어서 review_all을 사용했는데, 일부만 가져오는 것이 발생합니다.
사이트 기준으로 총 868개의 리뷰가 있는데, 그 중에  446개만 긁어오는 문제가 있습니다. sleep_milliseconds를 1000~5000까지 조정해봐도 같은 증상이 반복되는데 해결방법이 있을까요?

**Comment by JoMingyu** [comment]
Can you please submit code you wrote? It will helps for debugging.

**Comment by sociengineer** [comment]
My code is as follows:
#-*- coding:utf-8 -*-
from google_play_scraper import reviews_all, Sort
results = reviews_all(
    'com.hyundaicard.weather',
    count=10000,
    sleep_milliseconds=1000, # defaults to 0
    lang='ko', 
    country='kr', 
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT
    # filter_score_with=5 # defaults to None(means all score)
)

**Comment by JoMingyu** [comment]
related to #50 

`reviews` and `reviews_all` function scrape reviews with content. People can post review with star rating only(without review contents). These reviews aggregated for `total reviews` in Google Play, but don't displayed to review list.

**Comment by sociengineer** [comment]
I couldn't imagine almost half of user rate the application without any comments. Thank you for your kind explanation.

**Comment by JoMingyu** [comment]
Thank you for you report. I'll add some additional explanation to README.md for helping misunderstanding about Google Play review feature like this
