### ISSUE TITLE
all reviews score are 5

### ISSUE THREAD

**Issue by yasso50** [JoMingyu/google-play-scraper#60]
hi, thank you for this amazing library, I noticed that all the reviews' scores are 5 Stars don't know why in several apps, like Vodafone Egypt, please fix this. thanks again :).

**Comment by JoMingyu** [comment]
Can you please submit code you wrote? It will helps for debugging.

**Comment by yasso50** [comment]
I am really sorry m I didn't notice that there is an option to scrape all scores (1-5), this is a really fantastic library, really thank you very very much.

**Comment by JoMingyu** [comment]
I'll close this!
