### ISSUE TITLE
In-app Products

### ISSUE THREAD

**Issue by yoannes** [JoMingyu/google-play-scraper#61]
Hi,

This is very nice package, helped me a lot.

In my case I also needed the `In-app Products`

so I added at `constants/element.py`

```
"inAppProducts": ElementSpec(5, [0, 12, 12, 0]),
```

In case anyone else also needs it 😀

**Comment by JoMingyu** [comment]
It added to version 0.0.3.2 named `inAppProductPrice`. Thanks to your nice idea!

**Comment by yoannes** [comment]
Nice 😀

Thankyou 🙏🏽
