### ISSUE TITLE
Python setup.py egginfo

### ISSUE THREAD

**Issue by XangoXML** [JoMingyu/google-play-scraper#62]
Hi!!!

I got this error:  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-in
stall-Y33MgU/google-play-scraper/      

Any solution??? 
Thanks!!

**Comment by JoMingyu** [comment]
Can you install this after `pip install --upgrade setuptools`?

**Comment by JoMingyu** [comment]
I will close the issue. If it recurs, reopen and tag me.
