### ISSUE TITLE
Chrome can not start downloading before I move the mouse

### ISSUE THREAD

**Issue by WangGuox1n** [JoMingyu/google-play-scraper#63]
I use Chrome(on MacOS) to download the app, and Chrome can connect to the download website, but I have to move the mouse to active Chrome to start the download. Why?

**Comment by JoMingyu** [comment]
Is this a valid issue? This project is just a scraping library.

**Comment by JoMingyu** [comment]
I'll close this. If the issue is truly related to this project, reopen and tag me.
