### ISSUE TITLE
Review counts mismatch between reviews_all and app

### ISSUE THREAD

**Issue by arunkumarchan** [JoMingyu/google-play-scraper#65]
The total review count numbers are different between reviews_all method and app method, whereas the expectation is both the numbers should match. Please refer the below for reference

_from google_play_scraper import app
app(
    'com.zoho.crm',
    lang='en', # defaults to 'en'
    country='us' # defaults to 'us'
)['reviews']_

*1446*

_from google_play_scraper import Sort, reviews_all
result = reviews_all(
        'com.zoho.crm',
        sleep_milliseconds=0, # defaults to 0
        lang='en', # defaults to 'en'
        country='us', # defaults to 'us'
        sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT
        filter_score_with=None # defaults to None(means all score)
    )
len(result)_

*866*

**Comment by JoMingyu** [comment]
related to #50 

`reviews` and `reviews_all` function scrape reviews with content. People can post review with star rating only(without review contents). These reviews aggregated for total reviews in Google Play, but don't displayed to review list.

**Comment by JoMingyu** [comment]
The issue is stale, so I'll close it. If the issue recurs or you have more questions, reopen and tag me.
