### ISSUE TITLE
[BUG] JSONDecodeError          

### ISSUE THREAD

**Issue by erwanlenagard** [JoMingyu/google-play-scraper#67]
Hello,

I'd like to report a bug. When you execute your app() function as explained in the documentation, the query returns a JSONDecodeError. Please, could you explain me how to resolve this ?

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-25-ac438a877f44> in <module>
     31     query['url'],
     32     lang=query['lang'], # defaults to 'en'
---> 33     country=query['country'] # defaults to 'us'
     34     )
     35     print(result_app)

C:\Anaconda3\lib\site-packages\google_play_scraper\features\app.py in app(app_id, lang, country)
     24             key = key_match[0]
     25             value = json.loads(value_match[0])
---> 26 
     27             res[key] = value
     28 

C:\Anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

C:\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    338         end = _w(s, end).end()
    339         if end != len(s):
--> 340             raise JSONDecodeError("Extra data", s, end)
    341         return obj
    342 

JSONDecodeError: Extra data: line 220 column 1 (char 6960)

**Comment by DanielOX** [comment]
Yes, @JoMingyu  Kindly look at this issue,

**Comment by JoMingyu** [comment]
Please give me the result of running the following code on your device.

```python
from google_play_scraper import __version__

print(__version__)
```

If the result is not `0.1.1`, retry your code after run this command: `pip install google-play-scraper --upgrade`.
