### ISSUE TITLE
[BUG] JSONDecodeError

### ISSUE THREAD

**Issue by bettermesol** [JoMingyu/google-play-scraper#70]
**google_play_scraper.VERSION**
I did not check the exact version number, but I am sure that it is the latest, cuz I just installed google-play-scarper with PIP again. 

**Describe the bug**
I'd like to report another bug. The query returns a JSONDecodeError when I tried to run the sample code described in readme.md. Do you have a plan to update to solve this problem?

**Code**
from google_play_scraper import app

result = app(
    'com.nianticlabs.pokemongo',
    lang='en', # defaults to 'en'
    country='us' # defaults to 'us'
)

**Expected behavior**
The same result as shown in readme.md

but I got the unexpected error code as follows:
JSONDecodeErrorTraceback (most recent call last)
<ipython-input-60-ac546ce1c306> in <module>
      1 app('com.nianticlabs.pokemongo',
      2     lang='en', # defaults to 'en'
----> 3     country='us' # defaults to 'us'
      4    )

/opt/conda/lib/python3.7/site-packages/google_play_scraper/features/app.py in app(app_id, lang, country)
     24         if key_match and value_match:
     25             key = key_match[0]
---> 26             value = json.loads(value_match[0])
     27 
     28             res[key] = value

/opt/conda/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

/opt/conda/lib/python3.7/json/decoder.py in decode(self, s, _w)
    338         end = _w(s, end).end()
    339         if end != len(s):
--> 340             raise JSONDecodeError("Extra data", s, end)
    341         return obj
    342 

JSONDecodeError: Extra data: line 202 column 1 (char 6038)

**Comment by JoMingyu** [comment]
Please give me the result of running the following code on your device.

```python
from google_play_scraper import __version__

print(__version__)
```

If the result is not `0.1.1`, retry your code after run this command: `pip install google-play-scraper --upgrade`.

**Comment by bettermesol** [comment]
Sorry for the late reply.

I upgraded the package by running `pip install google-play-scraper --upgrade`,
and I checked that I am using the latest version based on the output saying "Successfully installed google-play-scraper-0.1.1".
(By the way, the `print(__version__)` is keep saying ", I am using "0.0.3.1".
Even though, I did upgrade and re-install to make sure.)

And then, I tried the following commands, but I still get the same error message.
Here are the full code and the result.
```
> from google_play_scraper import app
> app('com.nianticlabs.pokemongo', lang='en', country='us')

JSONDecodeErrorTraceback (most recent call last)
<ipython-input-21-618d3e3a5310> in <module>
----> 1 app('com.nianticlabs.pokemongo', lang='en', country='us')

/opt/conda/lib/python3.7/site-packages/google_play_scraper/features/app.py in app(app_id, lang, country)
     24             key = key_match[0]
     25             value = json.loads(value_match[0])
---> 26 
     27             res[key] = value
     28 

/opt/conda/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

/opt/conda/lib/python3.7/json/decoder.py in decode(self, s, _w)
    338         end = _w(s, end).end()
    339         if end != len(s):
--> 340             raise JSONDecodeError("Extra data", s, end)
    341         return obj
    342 

JSONDecodeError: Extra data: line 202 column 1 (char 6038)
```

**Comment by JoMingyu** [comment]
Since it is a library that is heavily influenced by the data structure of the play store, it is highly dependent on the version. I hope that you can re-install in a clean virtualenv to find out if the problem with the latest version of the library is correct.

**Comment by JoMingyu** [comment]
Sorry for the late reply. Mailing didn't work properly.

**Comment by JoMingyu** [comment]
stale
