### ISSUE TITLE
[FEAT-REQ] add Editors' Choice

### ISSUE THREAD

**Issue by elenaroot** [JoMingyu/google-play-scraper#71]
Would be very useful to add Editors' Choice data about app.

**Comment by JoMingyu** [comment]
Are you talking about [this](https://play.google.com/store/apps/editors_choice?hl=en)?

**Comment by elenaroot** [comment]
Yes, each app has this field (True/False). <span class="dMMEE">Editors' Choice</span>
Should be added to ElementSpecs

**Comment by JoMingyu** [comment]
I'll comment here after build some tech spec with API designs. The first user will be you, so I would appreciate it if you review API designs..

**Comment by elenaroot** [comment]
hey, any updates?

**Comment by JoMingyu** [comment]
ooh.. sorry. @elenaroot 
I read the issue again, and it seems that the `editors choice` information should be added to the return of the app function. Am i right? like..

```python
>>> app('some.app')
{..., "editorsChoice": True", ...}
```

**Comment by elenaroot** [comment]
you need to add `ElementSpecs.Detail['editorsChoice'] = ElementSpec(5, [0, 12, 15, 0], bool, False)`

**Comment by JoMingyu** [comment]
I'll apply it today. I am sorry for not being able to manage for a while due to my circumstances.

**Comment by JoMingyu** [comment]
It released at version [0.1.2](https://pypi.org/project/google-play-scraper/0.1.2/).
