### ISSUE TITLE
[BUG] contentRating is always wrong

### ISSUE THREAD

**Issue by thousandsofthem** [JoMingyu/google-play-scraper#75]
**google_play_scraper.VERSION**
'0.1.2'

**Describe the bug**

contentRating is always wrong
Example:

https://play.google.com/store/apps/details?id=org.telegram.messenger

Actual contentRating on page is:
  
  * `Rated for 12+` (Parental Guidance Recommended)

lib's output:
```
"contentRating": "Mature 17+",
"contentRatingDescription": null, 
```

**Code**

```
import google_play_scraper
output = google_play_scraper.app("org.telegram.messenger", lang="en", country="us")

>>> output["contentRating"]
'Mature 17+'
```

**Comment by JoMingyu** [comment]
I'll handle it. response due: 2021-01-10

**Comment by JoMingyu** [comment]
It is non-issue.

- app `Telegram` is `Mature 17+` in `us` now. In some countries, ratings are set differently, so it might be mistaken.
- You can check it out in https://play.google.com/store/apps/details?id=org.telegram.messenger&gl=us&hl=en
