### ISSUE TITLE
[BUG] Review scraping getting stuck

### ISSUE THREAD

**Issue by SimplyLucKey** [JoMingyu/google-play-scraper#77]
I have the following code and I cannot scrape the reviews beyond second or third app (of the first package). I have 10 apps per each package. 

![image](https://user-images.githubusercontent.com/35954092/103755828-50ef2900-4fc3-11eb-8df1-210b3f594d2b.png)

```
free_app_packages = [
    'com.innersloth.spacemafia',
    'com.pixelbox.roofrails',
    'com.playstrom.dop2',
#     'com.sushirolls.app',
    'com.iec.imposter.solo.kill',
    'com.lebleby.gearrace3d',
    'com.h8games.DoodleRun3D',
    'com.roblox.client',
    'com.constructor.games',
    'com.studio501.jumpdunk',
    'com.mglstudio.boyvsblocks'
]
```

**Comment by JoMingyu** [comment]
It looks like it's trying to crawl 10 times per app. Since all functions provided by the library execute web requests more than once, it is recommended to reduce the number of absolute function calls or perform concurrency through `aiohttp`.

**Comment by JoMingyu** [comment]
It is just the limit of blocking io.
