### ISSUE TITLE
[BUG] Issue while installing 0.2 version via pip

### ISSUE THREAD

**Issue by lalitpagaria** [JoMingyu/google-play-scraper#83]
Thank you for this awesome library. I am using it my project [Obsei](https://github.com/lalitpagaria/obsei).
Recently when I upgraded to latest release I got error. See below information
 
**google_play_scraper.VERSION**
Write result of `google_play_scraper.VERSION`

**Describe the bug**
Unable to install/upgrade latest version. Installing via version pinning giving me error.

**Code**
Copy and paste the code that have issue.

```
% pip install google-play-scraper==0.2
ERROR: Could not find a version that satisfies the requirement google-play-scraper==0.2
ERROR: No matching distribution found for google-play-scraper==0.2
```

**Expected behavior**
It should install latest version

**Additional context**

**Comment by JoMingyu** [comment]
There seems to be a problem during the release process. I'll release a new version and check if it's installed properly, and we'll notify you ASAP.

**Comment by JoMingyu** [comment]
@lalitpagaria 
Can I test the installation of version 0.2.1? I released it a little while ago.

**Comment by lalitpagaria** [comment]
@JoMingyu thanks for the fix
I will test out and let you know

**Comment by lalitpagaria** [comment]
@JoMingyu new version is installing correct. Thank you for support.
Closing this issue.

**Comment by JoMingyu** [comment]
great!
