### ISSUE TITLE
Recent reviews on UI (play store app) do not exist in response sorted by newest

### ISSUE THREAD

**Issue by zahra-ash0uri** [JoMingyu/google-play-scraper#85]
I have a continuation token like this:
`
{
    "token":  "xxxxxx",
    "lang": "fa",
    "country": "ir",
    "sort": 2,
    "count": 100,
    "filter_score_with": null 
}
`
What I wonder about is the returned reviews are at newest date-time but they are not visible on UI, I mean on play store itself.

**Comment by JoMingyu** [comment]
Can you give me code you used?

**Comment by JoMingyu** [comment]
stale
