### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ksralter** [JoMingyu/google-play-scraper#95]
**google_play_scraper.1.0.0**
 `google_play_scraper.1.0.0`

**Describe the bug**
it showing 'invalid decoded string length' warning while using application attribute.

**Code**
apk = APK(app)
x= apk.application

**Additional context**
 I also tried get_app_name() and this also gives same warning

**Comment by JoMingyu** [comment]
Your code example mismatches with this library. Perhaps you used another lib.
