### ISSUE TITLE
[FEAT-REQ] App search feature

### ISSUE THREAD

**Issue by imDivu** [JoMingyu/google-play-scraper#96]
Please Add Feature Like We Can Search App With App Name & Result Is Also In List!!!

Example:

results = search("Facebook")
For result in results:
   print (result['appid'])
   print (result['title'])
   print(result['description']
    Etc.............

**Comment by JoMingyu** [comment]
ok, I will add search feature implementation to next release cut.

**Comment by yoeldk** [comment]
Hi @JoMingyu ,

Any estimation when will the search feature be added?

Thanks!

**Comment by baguse** [comment]
Hi @JoMingyu, any update for this feature right now?? Thank you!

**Comment by anjaseidel** [comment]
Hi @JoMingyu, it would be great if you could implement this feature. The alternative python package with this functionality (https://github.com/danieliu/play-scraper) has not received any updates for two years and no longer works after the latest changes in the Google Playstore. Thus, all python lovers are a little lost.

**Comment by JoMingyu** [comment]
Sorry guys. It's hard to deal with because I'm busy with my main job. I'll try to do it as soon as possible, but we don't know the exact schedule. I would be very grateful if you could help through PR, etc.

**Comment by JoMingyu** [comment]
It released at version 1.2.0. Special thanks to @anjaseidel .
