### ISSUE TITLE
Confusing result["updated"] value format

### ISSUE THREAD

**Issue by koralturkk** [JoMingyu/google-play-scraper#97]
Hello, I really liked the package and it has been very useful. Thanks for taking time to putting in such work. I was wondering what is the format of  the value of result["updated"]. I had a hard time trying to convert it into datetime object. I was hoping maybe you can provide some answers

**Comment by JoMingyu** [comment]
It is a timestamp. You can convert at [Epoch Converter](https://www.epochconverter.com/).

or programmatically, you can use `datetime.fromtimestamp`. Python code example:

```python
from datetime import datetime

from google_play_scraper import app

result = app('com.nianticlabs.pokemongo', 'ko', 'kr')

o = datetime.fromtimestamp(result['updated'])

print(o)
```

result: 2021-07-31 08:16:09
