### ISSUE TITLE
[FEAT-REQ] Provide progress bar when calling reviews_all

### ISSUE THREAD

**Issue by lahdjirayhan** [JoMingyu/google-play-scraper#98]
**Is your feature request related to a problem? Please describe.**
It takes quite a long time to scrape all reviews of an app, and I'm not sure how long should I wait.

**Describe the solution you'd like**
It will be nice to have progress bar or at least some kind of report that tells how many reviews have been scraped, and if possible, how many reviews are left unscraped yet.

**Comment by lahdjirayhan** [comment]
While I was playing around with the idea of making a progress bar, I noticed that I can't reliably know how many reviews are actually there for an app. This is because I've been getting inconsistent results explained as follows:

Consider the example for app 'com.easytech.iron.android'

1. When I visit the Google Play through my Android phone and my PC browser, it shows that there are 13,854 reviews for the app.
2. When I use:
```
from google_play_scraper import app

app('com.easytech.iron.android', lang='en', country='us')['reviews']
```
It says there are 3778 reviews.

3. When I do
```
from google_play_scraper import reviews_all
gog3_reviews = reviews_all('com.easytech.iron.android', lang='en', country='us')
len(gog3_reviews)
```
It instead gives another number, 911.

I think the number of reviews given by method 1 does not discriminate language/country thus is the highest number. I think if all language and all countries are scraped, eventually I can get to number given by method 1. (I'm not sure, it's just a lazy guess.)

However, I am baffled as to why method 2 and 3 gives different result.

Is this behavior above expected? Is there explanation as to why it happens?

**Comment by JoMingyu** [comment]
It looks weird to me too. I'll review it in this release and let you know in the comments what the problem was and if it was fixed.

**Comment by JoMingyu** [comment]
Building a progress bar seems to be outside the responsibility of this library. I will close the issue.
